# Generated by Django 4.2.4 on 2023-09-22 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0020_alter_course_author_alter_course_backplate_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_result',
                 models.IntegerField(blank=True, default=None, null=True, verbose_name='Результаты теста')),
                ('homework_result',
                 models.IntegerField(blank=True, default=None, null=True, verbose_name='Результаты Д/З')),
                ('homework_comment',
                 models.TextField(blank=True, max_length=255, null=True, verbose_name='Комментарий к работе')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homework',
                                               verbose_name='Д/З')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
            },
        ),
    ]
