# Generated by Django 4.2.4 on 2023-09-22 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0020_alter_course_author_alter_course_backplate_color_and_more'),
        ('courses_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatistics',
            name='homework',
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson',
                                    verbose_name='Д/З'),
            preserve_default=False,
        ),
    ]
