# Generated by Django 4.2.4 on 2023-09-24 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('courses_statistics', '0005_alter_userstatistics_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatistics',
            old_name='attempts',
            new_name='exam_attempts',
        ),
    ]
