# Generated by Django 4.2.4 on 2023-09-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses_statistics', '0006_rename_attempts_userstatistics_exam_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistics',
            name='status',
            field=models.CharField(default='Доступно', max_length=15, verbose_name='Статус'),
        ),
    ]
