# Generated by Django 4.2.4 on 2023-09-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses_statistics', '0007_userstatistics_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistics',
            name='is_exam_complete',
            field=models.BooleanField(default=False, verbose_name='Тест решен?'),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='is_homework_checked',
            field=models.BooleanField(default=False, verbose_name='Д/З проверено?'),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='is_homework_complete',
            field=models.BooleanField(default=False, verbose_name='Д/З сдано?'),
        ),
    ]
