# Generated by Django 4.2.4 on 2023-09-29 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0021_homework_homework_max_result'),
        ('courses_statistics', '0009_alter_userstatistics_exam_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistics',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson',
                                    verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
