# Generated by Django 4.2.4 on 2023-09-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses_statistics', '0010_alter_userstatistics_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistics',
            name='homework_upload_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/homework/user/',
                                   verbose_name='Файл с Д/З'),
        ),
    ]
