# Generated by Django 4.2.4 on 2023-10-01 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0021_homework_homework_max_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_statistics', '0011_userstatistics_homework_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistics',
            name='is_lesson_opened',
            field=models.BooleanField(default=False, verbose_name='Урок был открыт? (не менять)'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='exam_attempts',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True,
                                                   verbose_name='Количество попыток (не менять)'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='exam_result',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Результаты теста (не менять)'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='homework_upload_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/homework/user/',
                                   verbose_name='Файл с Д/З (не менять)'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='is_exam_complete',
            field=models.BooleanField(default=False, verbose_name='Тест решен? (не менять)'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='is_homework_complete',
            field=models.BooleanField(default=False, verbose_name='Д/З сдано? (не менять)'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson',
                                    verbose_name='Урок (не менять)'),
        ),
        migrations.AlterField(
            model_name='userstatistics',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (не менять)'),
        ),
    ]
