# Generated by Django 4.2.5 on 2023-10-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_statistics', '0014_userstatistics_last_time_lesson_opened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatistics',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Выполнено? (не менять)'),
        ),
    ]
