# Generated by Django 4.2.4 on 2023-08-31 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='Название теста')),
            ],
            options={
                'verbose_name': 'Тестирование',
                'verbose_name_plural': 'Тестирование',
            },
        ),
        migrations.CreateModel(
            name='ExaminationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=255, verbose_name='Вопрос')),
                ('question_image',
                 models.ImageField(blank=True, default=None, null=True, upload_to='lessons/exams/images',
                                   verbose_name='Изображение (необязательно)')),
                ('right_answer', models.CharField(max_length=63, verbose_name='Правильный ответ')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examination',
                                           verbose_name='Тестирование')),
            ],
            options={
                'verbose_name': 'Тестовый вопрос',
                'verbose_name_plural': 'Тестовые вопросы',
            },
        ),
        migrations.CreateModel(
            name='ExaminationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=63, verbose_name='Ответ')),
                ('question',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examinationquestion',
                                   verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
