# Generated by Django 4.2.4 on 2023-09-16 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0013_alter_lesson_title_alter_lesson_video_youtube'),
        ('examination', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationquestion',
            name='exam',
        ),
        migrations.AddField(
            model_name='examinationquestion',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson',
                                    verbose_name='Урок'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Examination',
        ),
    ]
