# Generated by Django 4.2.4 on 2023-09-16 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0013_alter_lesson_title_alter_lesson_video_youtube'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examination', '0003_remove_examinationquestion_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinationquestion',
            name='lesson',
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='Название теста')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                             verbose_name='Автор')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson',
                                             verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Тестирование',
                'verbose_name_plural': 'Тестирование',
            },
        ),
        migrations.AddField(
            model_name='examinationquestion',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='examination.examination', verbose_name='Тестирование'),
            preserve_default=False,
        ),
    ]
