# Generated by Django 4.2.4 on 2023-09-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('examination', '0005_remove_examination_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationanswer',
            name='answer',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Ответ'),
        ),
    ]
