# Generated by Django 4.2.4 on 2023-09-24 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('examination', '0006_alter_examinationanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=1, validators=[
                django.core.validators.MaxValueValidator(limit_value=10, message='Максимальное кол-во попыток: 10!')],
                                                   verbose_name='Количество попыток'),
        ),
    ]
