# Generated by Django 4.2.4 on 2023-09-24 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('examination', '0007_examination_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=1, validators=[
                django.core.validators.MaxValueValidator(limit_value=10,
                                                         message='Максимальное количество попыток: 10')],
                                                   verbose_name='Количество попыток'),
        ),
    ]
