# Generated by Django 4.2.4 on 2023-09-24 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('examination', '0008_alter_examination_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='attempts',
            new_name='max_attempts',
        ),
    ]
