# Generated by Django 4.2.4 on 2023-09-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('examination', '0009_rename_attempts_examination_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationanswer',
            name='is_answer_right',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ?'),
        ),
    ]
