# Generated by Django 4.2.4 on 2023-09-02 10:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteurl',
            name='url',
            field=models.CharField(default='https://icodely.ru/invite?url=37eacaab-adc9-4f4f-8770-ef49591c0c79',
                                   max_length=127),
        ),
        migrations.AlterField(
            model_name='inviteurl',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course',
                                    verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='inviteurl',
            name='invite_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False,
                                   verbose_name='UUID'),
        ),
    ]
