# Generated by Django 4.2.4 on 2023-09-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0005_alter_inviteurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteurl',
            name='url',
            field=models.CharField(
                default='https://icodely.ru/invite?url=<bound method Field.value_to_string of <django.db.models.fields.UUIDField>>',
                max_length=127),
        ),
    ]
