# Generated by Django 4.2.4 on 2023-09-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0006_alter_inviteurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteurl',
            name='url',
            field=models.CharField(max_length=127),
        ),
    ]
