# Generated by Django 4.2.4 on 2023-09-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0008_alter_inviteurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertocourse',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
