# Generated by Django 4.2.4 on 2023-09-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0010_lesson_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_url',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Ссылка на Д/З'),
        ),
    ]
