# Generated by Django 4.2.4 on 2023-09-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0011_lesson_homework_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.AddField(
            model_name='lesson',
            name='short_description',
            field=models.TextField(default='test', max_length=63, verbose_name='Краткое описание шага урока'),
            preserve_default=False,
        ),
    ]
