# Generated by Django 4.2.4 on 2023-09-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('examination', '0005_remove_examination_lesson'),
        ('courses', '0013_alter_lesson_title_alter_lesson_video_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='exam_homework',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='examination.examination', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(max_length=4095, verbose_name='Содержание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='short_description',
            field=models.TextField(max_length=63, verbose_name='Краткое описание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=57, verbose_name='Название урока'),
        ),
    ]
