# Generated by Django 4.2.4 on 2023-09-21 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0017_alter_homework_options_alter_homework_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='test',
            new_name='exam',
        ),
    ]
