# Generated by Django 4.2.4 on 2023-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0018_rename_test_homework_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, max_length=53, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='backplate_color',
            field=models.CharField(
                choices=[('yellow', 'Желтый'), ('pink', 'Розовый'), ('blue', 'Голубой'), ('gray', 'Серый')],
                default='gray', max_length=6, verbose_name='Цвет подкладки'),
        ),
    ]
