# Generated by Django 4.2.4 on 2023-09-22 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import usermanager.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0019_course_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(default=usermanager.models.CustomUser, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Автор курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='backplate_color',
            field=models.CharField(
                choices=[('gray', 'Серый'), ('yellow', 'Желтый'), ('pink', 'Розовый'), ('blue', 'Голубой')],
                default='gray', max_length=6, verbose_name='Цвет подкладки'),
        ),
        migrations.AlterField(
            model_name='usertocourse',
            name='course',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='courses.course',
                                    verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='usertocourse',
            name='invite_uuid',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='courses.inviteurl',
                                    verbose_name='UUID приглашения(ссылки)'),
        ),
        migrations.AlterField(
            model_name='usertocourse',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
