# Generated by Django 4.2.4 on 2023-10-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0021_homework_homework_max_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='full_price',
        ),
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Длительность курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='month_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True,
                                                   verbose_name='Цена в месяц за курс'),
        ),
    ]
