# Generated by Django 4.2.4 on 2023-10-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0022_rename_price_course_full_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='steps',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество шагов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Длительность курса (в мес.)'),
        ),
    ]
