# Generated by Django 4.2.5 on 2023-10-13 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('examination', '0011_alter_examinationquestion_question'),
        ('courses', '0023_course_steps_alter_course_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='examination.examination', unique=True, verbose_name='Тестирование'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='courses.homework', unique=True, verbose_name='Д/З'),
        ),
    ]
