# Generated by Django 4.2.5 on 2023-10-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('examination', '0011_alter_examinationquestion_question'),
        ('courses', '0024_alter_homework_exam_alter_lesson_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='exam',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                       to='examination.examination', verbose_name='Тестирование'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT,
                                       to='courses.homework', verbose_name='Д/З'),
        ),
    ]
