# Generated by Django 4.2.6 on 2023-10-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_homework_exam_alter_lesson_homework'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackplateCourseColor',
        ),
    ]
